# Site settings
title: Partially Derivative
description: The data of the world around us
baseurl: # the subpath of your site, e.g. /blog
url: http://partiallyderivative.com # the base hostname & protocol for your site e.g.

# User settings
username: Partially Derivative
user_description: The data of the world around us.
user_title: Partially Derivative
email: hello@partiallyderivative.com
twitter_username: partiallyd
github_username:  partiallyderivative

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
mathjax: true


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true

links_podcast:
  - title: Podcast
    url: /podcast
  - title: Podcast Feed
    url: /podcast.xml

links_top:
    - title: Home
      url: /
    - title: About
      url: /about
    - title: Sponsors
      url: /sponsors

links_blog:
  - title: Blog
    url: /blog
  - title: Blog Feed
    url: /blog.xml


links_dataloveletters:
  - title: Read Past Issues
    url: /loveletters

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Podcast settings
podcast_url: http://www.partiallyderivative.com
podcast_album_art: /assets/img/partiallyd_title.png
podcast_title: Partially Derivative
podcast_owner: Partially Derivative
podcast_creator: Jonathon Morgan
podcast_email: jonathonmorgan@gmail.com
podcast_category: Technology
podcast_subcategory_one: IT News
podcast_subcategory_two: Software How-To
podcast_explicit: "yes"
podcast_author: Partially Derivative
podcast_description: The data of the world around us, hosted by data science super geeks. For the nerdy and nerd curious.
podcast_summary: Partially Derivative is a weekly podcast from the founders of Popily. We geek out about silly data stories, interview fun people doing interesting work, and drink beer.
podcast_subtitle: A podcast about the data of everything.


authors:
  chrisalbon:
    name: Chris Albon
    display_name: Chris Albon
    bio: Chris is a political scientist, data scientist, and co-host of Partially Derivative.
    email: chris@popily.com
    web: http://chrisalbon.com
    twitter: chrisalbon
    github: chrisalbon
    photo: chris_cartoon.png
  partiallyderivative:
    name: partiallyderivative
    display_name: Partially Derivative
    bio: Partially Derivative is a podcast about data science hosted by Chris Albon, Jonathon Morgan, and Vidya Spandana.
    email: hello@partiallyderivative.com
    web: http://partiallyderivative.com
    twitter: partiallyd
    github: partyiallyderivative
    photo: pd_heart_logo_200x200.png
